<a href="https://colab.research.google.com/github/addamit/LMExperiments/blob/main/attention_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch

In [ ]:
E = torch.tensor([
    [0.1, 0.2, 0.3, 0.4],  # token 10
    [0.2, 0.3, 0.4, 0.5],  # token 20
    [0.3, 0.4, 0.5, 0.6],  # token 30
    [0.4, 0.5, 0.6, 0.7],  # token 40
    [0.5, 0.6, 0.7, 0.8],  # token 50
    [0.6, 0.7, 0.8, 0.9]   # token 60
])
token_2 = E[1]
token_2

tensor([0.2000, 0.3000, 0.4000, 0.5000])

In [ ]:
r_2 = torch.dot(token_2, token_2)
r_22 = 0.2*0.2 + 0.3*0.3 + 0.4*0.4 + 0.5*0.5
r_2 == r_22

tensor(True)

In [ ]:

torch.dot(token_2, E[5])

tensor(1.1000)

In [ ]:
num_tokens = E.shape[0]

scores = torch.empty(num_tokens, num_tokens)
for i in range(num_tokens):
  for j in range(num_tokens):
    scores[i][j] = torch.dot(E[i], E[j])


In [ ]:
scores

tensor([[0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000],
        [0.4000, 0.5400, 0.6800, 0.8200, 0.9600, 1.1000],
        [0.5000, 0.6800, 0.8600, 1.0400, 1.2200, 1.4000],
        [0.6000, 0.8200, 1.0400, 1.2600, 1.4800, 1.7000],
        [0.7000, 0.9600, 1.2200, 1.4800, 1.7400, 2.0000],
        [0.8000, 1.1000, 1.4000, 1.7000, 2.0000, 2.3000]])

In [ ]:
scores.sum(dim=1)

tensor([3.3000, 4.5000, 5.7000, 6.9000, 8.1000, 9.3000])

In [ ]:
0.3 + 0.4 + 0.5 + 0.6 + 0.7 + 0.8

3.3

In [ ]:
weighted_scores = scores / scores.sum(dim=1)

In [ ]:
weighted_scores

tensor([[0.0909, 0.0889, 0.0877, 0.0870, 0.0864, 0.0860],
        [0.1212, 0.1200, 0.1193, 0.1188, 0.1185, 0.1183],
        [0.1515, 0.1511, 0.1509, 0.1507, 0.1506, 0.1505],
        [0.1818, 0.1822, 0.1825, 0.1826, 0.1827, 0.1828],
        [0.2121, 0.2133, 0.2140, 0.2145, 0.2148, 0.2151],
        [0.2424, 0.2444, 0.2456, 0.2464, 0.2469, 0.2473]])

In [ ]:
weighted_scores.sum(dim=1)

tensor([0.5269, 0.7161, 0.9054, 1.0946, 1.2839, 1.4731])

In [ ]:
weighted_scores = torch.softmax(scores, dim=1)
weighted_scores

tensor([[0.1279, 0.1414, 0.1562, 0.1727, 0.1908, 0.2109],
        [0.1142, 0.1313, 0.1510, 0.1737, 0.1999, 0.2299],
        [0.1014, 0.1214, 0.1454, 0.1740, 0.2083, 0.2494],
        [0.0897, 0.1118, 0.1393, 0.1735, 0.2163, 0.2695],
        [0.0790, 0.1025, 0.1329, 0.1723, 0.2235, 0.2899],
        [0.0693, 0.0935, 0.1262, 0.1704, 0.2300, 0.3105]])

In [ ]:
weighted_scores.sum(dim=1)

tensor([1., 1., 1., 1., 1., 1.])

In [ ]:
token_2_attentions = weighted_scores[1]
print(token_2_attentions.sum())
token_2_attentions

tensor(1.)


tensor([0.1142, 0.1313, 0.1510, 0.1737, 0.1999, 0.2299])

In [ ]:
context_vec = torch.zeros(1, 4) # calculating only 1 context vector for a given input token
for i in range(num_tokens):
  print(context_vec)
  context_vec += token_2_attentions[i]*E[i]
print(f"final context vec {context_vec}")

tensor([[0., 0., 0., 0.]])
tensor([[0.0114, 0.0228, 0.0342, 0.0457]])
tensor([[0.0377, 0.0622, 0.0868, 0.1113]])
tensor([[0.0830, 0.1226, 0.1623, 0.2019]])
tensor([[0.1525, 0.2095, 0.2665, 0.3236]])
tensor([[0.2524, 0.3294, 0.4064, 0.4835]])
final context vec tensor([[0.3903, 0.4903, 0.5903, 0.6903]])


In [ ]:
context_vec

tensor([[0.3903, 0.4903, 0.5903, 0.6903]])

In [ ]:
context_vecs = torch.zeros(num_tokens, 4) # All tokens. Each input is of size 4
for i in range(num_tokens):
  token_weighted_scores = weighted_scores[i]
  #print(token_weighted_scores)
  for j in range(num_tokens):
    context_vecs[i] += token_weighted_scores[j]*E[j]


In [ ]:
context_vecs

tensor([[0.3790, 0.4790, 0.5790, 0.6790],
        [0.3903, 0.4903, 0.5903, 0.6903],
        [0.4015, 0.5015, 0.6015, 0.7015],
        [0.4123, 0.5123, 0.6123, 0.7123],
        [0.4228, 0.5228, 0.6228, 0.7228],
        [0.4330, 0.5330, 0.6330, 0.7330]])

In [9]:
## More compact
import torch
import torch.nn as nn

In [10]:
# small vocab
vocab = {"<s>": 0, "I": 1, "like": 2, "AI": 3, ".": 4, "<pad>": 5, "<unk>": 6}
inv_vocab = {v: k for k, v in vocab.items()}


In [11]:
# lets write a tokenizer
def tokenize(text):
  tokens = text.split()
  token_ids = [vocab[token] if token in vocab else vocab["<unk>"] for token in tokens]
  return token_ids


In [12]:
text = "<s> I like AI ."
inputs = tokenize(text)
inputs

[0, 1, 2, 3, 4]

In [13]:
input_ids = torch.tensor(inputs)
input_ids, input_ids.shape

(tensor([0, 1, 2, 3, 4]), torch.Size([5]))

In [14]:
# token gets projected as embedding
embedding_weights = torch.tensor([
    [0.1, 0.2, 0.3, 0.4],  # token <s>
    [0.2, 0.3, 0.4, 0.5],  # token <I>
    [0.3, 0.4, 0.5, 0.6],  # token <like>
    [0.4, 0.5, 0.6, 0.7],  # token <AI>
    [0.5, 0.6, 0.7, 0.8],  # token <.>
    [0.6, 0.7, 0.8, 0.9]   # token <pad>
])

embedding_layer = nn.Embedding.from_pretrained(embedding_weights, freeze=True)


In [15]:
x = embedding_layer(input_ids)
x.shape

torch.Size([5, 4])

In [16]:
x

tensor([[0.1000, 0.2000, 0.3000, 0.4000],
        [0.2000, 0.3000, 0.4000, 0.5000],
        [0.3000, 0.4000, 0.5000, 0.6000],
        [0.4000, 0.5000, 0.6000, 0.7000],
        [0.5000, 0.6000, 0.7000, 0.8000]])

In [17]:
Wei_q = torch.tensor([  # Query weights
    [1.0, 0.5],
    [0.6, 0.3],
    [0.4, 0.2],
    [0.8, 0.7]
])

Wei_k = torch.tensor([  # Key weights
    [0.9, 0.2],
    [0.5, 0.4],
    [0.3, 0.8],
    [0.1, 0.6]
])

Wei_v = torch.tensor([  # Value weights
    [0.8, 0.3],
    [0.2, 0.5],
    [0.7, 0.4],
    [0.1, 0.9]
])

W_q = nn.Parameter(Wei_q, requires_grad=False)
W_k = nn.Parameter(Wei_k, requires_grad=False)
W_v = nn.Parameter(Wei_v, requires_grad=False)


In [18]:
# projection
Q = x @ W_q
K = x @ W_k
Q.shape, K.shape # All tokens are projected

(torch.Size([5, 2]), torch.Size([5, 2]))

In [19]:
scores = Q @ K.transpose(-1, -2)
scores


tensor([[0.4722, 0.6810, 0.8898, 1.0986, 1.3074],
        [0.6604, 0.9536, 1.2468, 1.5400, 1.8332],
        [0.8486, 1.2262, 1.6038, 1.9814, 2.3590],
        [1.0368, 1.4988, 1.9608, 2.4228, 2.8848],
        [1.2250, 1.7714, 2.3178, 2.8642, 3.4106]])

In [20]:
# Normalize the scores by the embedding dimension - "scaled dot product attention"
scores = scores / (K.shape[-1] ** 0.5)
scores

tensor([[0.3339, 0.4815, 0.6292, 0.7768, 0.9245],
        [0.4670, 0.6743, 0.8816, 1.0889, 1.2963],
        [0.6001, 0.8671, 1.1341, 1.4011, 1.6681],
        [0.7331, 1.0598, 1.3865, 1.7132, 2.0399],
        [0.8662, 1.2526, 1.6389, 2.0253, 2.4117]])

In [22]:
torch.dot(Q[0], K[0]) / (K.shape[-1] ** 0.5) # manually verifying with scores for one

tensor(0.3339)

In [23]:
attention_weights = torch.softmax(scores, dim=-1)
attention_weights

tensor([[0.1457, 0.1688, 0.1957, 0.2268, 0.2629],
        [0.1266, 0.1558, 0.1917, 0.2358, 0.2901],
        [0.1093, 0.1427, 0.1864, 0.2435, 0.3180],
        [0.0937, 0.1300, 0.1802, 0.2498, 0.3463],
        [0.0799, 0.1176, 0.1731, 0.2547, 0.3748]])

In [24]:
attention_weights.sum(dim=1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

In [25]:
# lets recreate the softmax logic for one row
import math
total_exp = math.exp(scores[0][0]) + math.exp(scores[0][1]) + math.exp(scores[0][2]) + math.exp(scores[0][3])
total_exp


7.065603615893195

In [26]:
row_wei = [math.exp(scores[0][0]) / total_exp, math.exp(scores[0][1]) / total_exp, math.exp(scores[0][2]) / total_exp, math.exp(scores[0][3]) / total_exp]
row_wei
row_wei_pt = torch.tensor(row_wei)
row_wei_pt.sum()

tensor(1.)

In [27]:
# packing it all together in a single line it looks like so:
# Scaled dot product attention
attention_scores = torch.softmax(Q @ K.transpose(-1, -2)/ K.shape[-1]**0.5 , dim=-1)
attention_scores

tensor([[0.1457, 0.1688, 0.1957, 0.2268, 0.2629],
        [0.1266, 0.1558, 0.1917, 0.2358, 0.2901],
        [0.1093, 0.1427, 0.1864, 0.2435, 0.3180],
        [0.0937, 0.1300, 0.1802, 0.2498, 0.3463],
        [0.0799, 0.1176, 0.1731, 0.2547, 0.3748]])

In [29]:
x.shape, W_v.shape

(torch.Size([5, 4]), torch.Size([4, 2]))

In [28]:
V = x @ W_v
V.shape

torch.Size([5, 2])

In [30]:
attention_output = attention_scores @ V  # Weighted sum of values
attention_output

tensor([[0.7827, 1.0914],
        [0.8033, 1.1155],
        [0.8233, 1.1388],
        [0.8425, 1.1612],
        [0.8608, 1.1826]])

In [31]:
# Lets see how the above is weighted average for one token
attention_weights_tok0 = attention_scores[0]
print(attention_weights_tok0)


tensor([0.1457, 0.1688, 0.1957, 0.2268, 0.2629])


In [34]:
contextvec_tok0 = torch.zeros(1,2)
contextvec_tok0
for i in range(V.shape[0]):
  contextvec_tok0 += attention_weights_tok0[i]*V[i]
contextvec_tok0 # this matches with attention_output[0]

tensor([[0.7827, 1.0914]])

In [37]:
# checking if two tensors are equal
torch.allclose(attention_output[0], contextvec_tok0)

True

In [38]:
## now lets learn how to hide future tokens
ones = torch.ones(attention_scores.shape)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [40]:
mask = torch.tril(ones)
mask

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [41]:
masked_attention_weights = attention_weights * mask
masked_attention_weights

tensor([[0.1457, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1266, 0.1558, 0.0000, 0.0000, 0.0000],
        [0.1093, 0.1427, 0.1864, 0.0000, 0.0000],
        [0.0937, 0.1300, 0.1802, 0.2498, 0.0000],
        [0.0799, 0.1176, 0.1731, 0.2547, 0.3748]])

In [45]:
row_sum = masked_attention_weights.sum(dim=-1)

In [48]:
row_sum.unsqueeze(-1)

tensor([[0.1457],
        [0.2824],
        [0.4385],
        [0.6537],
        [1.0000]])

In [49]:
causal_attention_weights = masked_attention_weights / row_sum.unsqueeze(-1)

In [51]:
causal_attention_weights.sum(dim=-1)

tensor([1., 1., 1., 1., 1.])

In [52]:
causal_attention_weights

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4484, 0.5516, 0.0000, 0.0000, 0.0000],
        [0.2493, 0.3256, 0.4252, 0.0000, 0.0000],
        [0.1434, 0.1988, 0.2756, 0.3821, 0.0000],
        [0.0799, 0.1176, 0.1731, 0.2547, 0.3748]])

In [59]:
mask = torch.triu(torch.ones(5, 5), diagonal=1)
mask

tensor([[0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.]])

In [60]:
mask.bool()

tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]])

In [62]:
attention_weights.masked_fill(mask.bool(), float('-inf'))

tensor([[0.1457,   -inf,   -inf,   -inf,   -inf],
        [0.1266, 0.1558,   -inf,   -inf,   -inf],
        [0.1093, 0.1427, 0.1864,   -inf,   -inf],
        [0.0937, 0.1300, 0.1802, 0.2498,   -inf],
        [0.0799, 0.1176, 0.1731, 0.2547, 0.3748]])

In [63]:
causal_attention_weights = torch.softmax(attention_weights.masked_fill(mask.bool(), float('-inf')), dim=-1)
causal_attention_weights

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4927, 0.5073, 0.0000, 0.0000, 0.0000],
        [0.3211, 0.3320, 0.3469, 0.0000, 0.0000],
        [0.2328, 0.2414, 0.2538, 0.2721, 0.0000],
        [0.1764, 0.1831, 0.1936, 0.2100, 0.2369]])

In [70]:

m = torch.triu(torch.ones(5, 5), diagonal=1)
m.bool()
t = torch.randn(5,5)
t.masked_fill(m.bool(), float('-inf'))


tensor([[-0.3347,    -inf,    -inf,    -inf,    -inf],
        [-0.8329, -0.4303,    -inf,    -inf,    -inf],
        [ 1.2636, -1.2162, -0.4066,    -inf,    -inf],
        [ 0.5300,  0.6473, -2.0347,  0.3024,    -inf],
        [ 0.7117, -1.1402,  2.3720,  0.3692,  0.1019]])

In [ ]:
class CausalAttention(nn.Module):

  def __init__(self, context_len, embedding_dim, head_dim, use_bias):
    super().__init__()
    self.head_dim = head_dim
    self.context_len = context_len
    self.query = nn.Linear(embedding_dim, head_dim, bias=use_bias)
    self.key   = nn.Linear(embedding_dim, head_dim, bias=use_bias)
    self.value = nn.Linear(embedding_dim, head_dim, bias=use_bias)
    self.register_buffer('mask', torch.triu(torch.ones(context_len, context_len), diagonal=1))

  def formard(self, x):

    q = self.query(x) # projecting x to q
    k = self.key(x)   # projecting x to k
    v = self.value(x) # projecting x to v

    scores = q @ k.transpose(-1, -2) / (self.head_dim ** 0.5)  # scaled dot product




In [ ]:
# Now, for a single attention head, let's define some example weight matrices:
W_q = torch.tensor([  # Query weights
    [1.0, 0.5],
    [0.6, 0.3],
    [0.4, 0.2],
    [0.8, 0.7]
])

W_k = torch.tensor([  # Key weights
    [0.9, 0.2],
    [0.5, 0.4],
    [0.3, 0.8],
    [0.1, 0.6]
])

W_v = torch.tensor([  # Value weights
    [0.8, 0.3],
    [0.2, 0.5],
    [0.7, 0.4],
    [0.1, 0.9]
])


Prefill phase is a compute bound issue.   

What does compute bound means?   

Constrained by the amount of compute available

1. Within each layer: During prefill, we are calculating the K, Q, and V matrices for the entire input sequence. However, the layer processing still follows a sequential pattern:

Within each layer: All token positions are processed in parallel
For each position, Q, K, V projections are calculated simultaneously
Attention scores for all positions are computed in parallel
2. Across layers: Processing happens sequentially

Layer 1 must complete for all tokens before Layer 2 can begin
Layer 2 must complete before Layer 3, and so on
Each subsequent layer takes as input the output of the previous layer
This sequential layer processing is necessary because each layer's input depends on the output of the previous layer. There's a data dependency that can't be parallelized away

During prefill, all K and V values are computed first for the entire input sequence

Then all attention calculations can happen in parallel, with each row using the appropriate subset of K and V values
The causal mask ensures each position only attends to current and previous positions

This shared access to K and V values doesn't break parallelism because we're not waiting for intermediate results of attention calculations - we're just sharing the input projections across all the parallel computations.

When we multiply two matrices, pytorch can internally parallelize the multiplication in multiple cpu cores. One way would be to internally use threads on separate cores and each thread will perform multiplication on a subset of columns and concatenate the columns into the final matrix.


In [ ]:
import os
import time
import torch

In [ ]:
rows,cols = 1000, 1000
A = torch.randn(rows, cols)
B = torch.randn(rows, cols)
start = time.time()
C = torch.matmul(A, B)
end = time.time()
print(f"time taken: {end-start}")

time taken: 0.042360782623291016


In [ ]:
C.shape

torch.Size([1000, 1000])

Lets hand roll one to understand better

In [ ]:
num_threads = 2
partition = cols // num_threads
partition
C1 = torch.matmul(A, B[:, :partition])
C2 = torch.matmul(A, B[:, partition:])

In [ ]:
C1.shape, C2.shape
C_ = torch.cat([C1, C2], dim=1)
C_.shape

torch.Size([1000, 1000])

In [ ]:
are_equal = torch.allclose(C, C_, atol=1e-3)
print(are_equal)

True


In [ ]:
# lets see how many threads are setup for torch
torch_thread_count = torch.get_num_threads()
print(f"torch threads: {torch_thread_count}")

# lets see how many cpu cores we have on
cores = os.cpu_count()
print(f"cpu cores: {cores}")

# now lets set the number of threads equaling the number of cores
torch.set_num_threads(cores)
torch_thread_count = torch.get_num_threads()
print(f"torch threads: {torch_thread_count}")



torch threads: 1
cpu cores: 2
torch threads: 2


In [ ]:

# now lets perform the same multiplication we did earlier except this time torch will leverage cores internally.
start = time.time()
C = torch.matmul(A, B)
end = time.time()
print(f"time taken: {end-start}")


time taken: 0.06766867637634277


In [ ]:
# now lets create large matrix for multiplication
N = 5000
A = torch.randn(N, N)
B = torch.randn(N, N)

# lets create a function to wrap things up so we can test different thread counts
def benchmark_matmul(num_threads):
    torch.set_num_threads(num_threads)
    start = time.time()
    C = torch.matmul(A, B)
    end = time.time()
    print(f"time taken: {end-start}")
    return end - start



In [ ]:
benchmark_matmul(num_threads=1)
benchmark_matmul(num_threads=2)
benchmark_matmul(num_threads=8) # if number of threads is more than num of cores the perfomance suffers


time taken: 3.727259635925293
time taken: 3.3741724491119385
time taken: 8.147592544555664


8.147592544555664

In [ ]:
# now lets see if we have a gpu, how can we make this faster
if torch.cuda.is_available():
    device = torch.device("cuda")
    A = A.to(device)
    B = B.to(device)
    start = time.time()
    C = torch.matmul(A, B)
    end = time.time()
    print(f"time taken: {end-start}")

In [ ]:
import torch
import math
import torch.nn as nn
import torch.nn.functional as F

Imagine we have the following input sequence tokens
[10, 20, 30, 40, 50, 60].

First, we convert these tokens into embeddings.

For simplicity, let's say our embedding table gives us:

Token 10 → [0.1, 0.2, 0.3, 0.4]  
Token 20 → [0.2, 0.3, 0.4, 0.5]  
Token 30 → [0.3, 0.4, 0.5, 0.6]  
Token 40 → [0.4, 0.5, 0.6, 0.7]  
Token 50 → [0.5, 0.6, 0.7, 0.8]  
Token 60 → [0.6, 0.7, 0.8, 0.9]  



In [ ]:
#Our embedding matrix E is now:
E = [
    [0.1, 0.2, 0.3, 0.4],  # token 10
    [0.2, 0.3, 0.4, 0.5],  # token 20
    [0.3, 0.4, 0.5, 0.6],  # token 30
    [0.4, 0.5, 0.6, 0.7],  # token 40
    [0.5, 0.6, 0.7, 0.8],  # token 50
    [0.6, 0.7, 0.8, 0.9]   # token 60
]

In [ ]:
# converting E into torch tensor
import torch
E = torch.tensor(E)
E.shape

torch.Size([6, 4])

In [ ]:
# Now, for a single attention head, let's define some example weight matrices:
W_q = torch.tensor([  # Query weights
    [1.0, 0.5],
    [0.6, 0.3],
    [0.4, 0.2],
    [0.8, 0.7]
])

W_k = torch.tensor([  # Key weights
    [0.9, 0.2],
    [0.5, 0.4],
    [0.3, 0.8],
    [0.1, 0.6]
])

W_v = torch.tensor([  # Value weights
    [0.8, 0.3],
    [0.2, 0.5],
    [0.7, 0.4],
    [0.1, 0.9]
])


In [ ]:
W_q.shape, W_k.shape, W_v.shape

(torch.Size([4, 2]), torch.Size([4, 2]), torch.Size([4, 2]))

In [ ]:
# Step 1: Calculate Q, K, V matrices
# For each token, compute Q, K, V vectors
Q = E @ W_q  # Shape: [6, 2]
K = E @ W_k  # Shape: [6, 2]
V = E @ W_v  # Shape: [6, 2]

In [ ]:
Q.shape, K.shape, V.shape

(torch.Size([6, 2]), torch.Size([6, 2]), torch.Size([6, 2]))

In [ ]:
# attention scores
attention_scores = Q @ K.transpose(-1, -2)
attention_scores = attention_scores / math.sqrt(2) # our d_k = 2


In [ ]:
attention_scores.shape

torch.Size([6, 6])

In [ ]:
attention_scores

tensor([[0.3339, 0.4815, 0.6292, 0.7768, 0.9245, 1.0721],
        [0.4670, 0.6743, 0.8816, 1.0889, 1.2963, 1.5036],
        [0.6001, 0.8671, 1.1341, 1.4011, 1.6681, 1.9351],
        [0.7331, 1.0598, 1.3865, 1.7132, 2.0399, 2.3665],
        [0.8662, 1.2526, 1.6389, 2.0253, 2.4117, 2.7980],
        [0.9993, 1.4453, 1.8914, 2.3374, 2.7835, 3.2295]])

In [ ]:
# Create causal mask (lower triangular matrix)
mask = torch.tril(torch.ones(6, 6))
mask

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
# Apply mask (set upper triangular part to -infinity)
masked_scores = attention_scores * mask + -1e9 * (1 - mask)
masked_scores

tensor([[ 3.3390e-01, -1.0000e+09, -1.0000e+09, -1.0000e+09, -1.0000e+09,
         -1.0000e+09],
        [ 4.6697e-01,  6.7430e-01, -1.0000e+09, -1.0000e+09, -1.0000e+09,
         -1.0000e+09],
        [ 6.0005e-01,  8.6705e-01,  1.1341e+00, -1.0000e+09, -1.0000e+09,
         -1.0000e+09],
        [ 7.3313e-01,  1.0598e+00,  1.3865e+00,  1.7132e+00, -1.0000e+09,
         -1.0000e+09],
        [ 8.6621e-01,  1.2526e+00,  1.6389e+00,  2.0253e+00,  2.4117e+00,
         -1.0000e+09],
        [ 9.9928e-01,  1.4453e+00,  1.8914e+00,  2.3374e+00,  2.7835e+00,
          3.2295e+00]])

In [ ]:
# Apply softmax row-wise
attention_weights = F.softmax(masked_scores, dim=1)  # Shape: [6, 6]
attention_weights

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4484, 0.5516, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2493, 0.3256, 0.4252, 0.0000, 0.0000, 0.0000],
        [0.1434, 0.1988, 0.2756, 0.3821, 0.0000, 0.0000],
        [0.0799, 0.1176, 0.1731, 0.2547, 0.3748, 0.0000],
        [0.0415, 0.0649, 0.1014, 0.1584, 0.2474, 0.3864]])

In [ ]:
# Context vectors = attention_weights @ V
context_vectors = attention_weights @ V  # Shape: [6, 2]

In [ ]:
context_vectors.shape

torch.Size([6, 2])

In [ ]:
kv_cache = {
    'K': K,  # Shape: [6, 2]
    'V': V   # Shape: [6, 2]
}

In [ ]:
kv_cache

{'K': tensor([[0.3200, 0.5800],
         [0.5000, 0.7800],
         [0.6800, 0.9800],
         [0.8600, 1.1800],
         [1.0400, 1.3800],
         [1.2200, 1.5800]]),
 'V': tensor([[0.3700, 0.6100],
         [0.5500, 0.8200],
         [0.7300, 1.0300],
         [0.9100, 1.2400],
         [1.0900, 1.4500],
         [1.2700, 1.6600]])}

In [ ]:
#  Parallelizing the QKV Projections
# Computing for token 10
Q_0 = E[0] @ W_q
K_0 = E[0] @ W_k
V_0 = E[0] @ W_v

# Computing for token 20
Q_1 = E[1] @ W_q
K_1= E[1] @ W_k
V_1 = E[1] @ W_v

# And so on...

In [ ]:
# For token 10
are_equal = torch.allclose(Q_0, Q[0], atol=1e-3)
print(are_equal) # they are the same

are_equal = torch.allclose(K_0, K[0], atol=1e-3)
print(are_equal) # they are the same

are_equal = torch.allclose(V_0, V[0], atol=1e-3)
print(are_equal) # they are the same


# For token 20
are_equal = torch.allclose(Q_1, Q[1], atol=1e-3)
print(are_equal) # they are the same

are_equal = torch.allclose(K_1, K[1], atol=1e-3)
print(are_equal) # they are the same

are_equal = torch.allclose(V_1, V[1], atol=1e-3)
print(are_equal) # they are the same


True
True
True
True
True
True


In [ ]:
import torch
import torch.nn.functional as F
import math
from transformers import GPT2Model, GPT2Config, GPT2Tokenizer

In [ ]:
# Load pre-trained GPT2 model
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2Model.from_pretrained('gpt2')
model.eval()  # S

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

GPT2Model(
  (wte): Embedding(50257, 768)
  (wpe): Embedding(1024, 768)
  (drop): Dropout(p=0.1, inplace=False)
  (h): ModuleList(
    (0-11): 12 x GPT2Block(
      (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (attn): GPT2Attention(
        (c_attn): Conv1D(nf=2304, nx=768)
        (c_proj): Conv1D(nf=768, nx=768)
        (attn_dropout): Dropout(p=0.1, inplace=False)
        (resid_dropout): Dropout(p=0.1, inplace=False)
      )
      (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (mlp): GPT2MLP(
        (c_fc): Conv1D(nf=3072, nx=768)
        (c_proj): Conv1D(nf=768, nx=3072)
        (act): NewGELUActivation()
        (dropout): Dropout(p=0.1, inplace=False)
      )
    )
  )
  (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
)

In [ ]:
# Sample input
text = "Hello, this is a test of the prefill phase."
input_ids = tokenizer.encode(text, return_tensors='pt')


In [ ]:
input_ids.shape

torch.Size([1, 12])

In [ ]:
# Extract single layer params (let's use the first layer)
layer_idx = 0
layer = model.h[layer_idx]

In [ ]:

layer

GPT2Block(
  (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  (attn): GPT2Attention(
    (c_attn): Conv1D(nf=2304, nx=768)
    (c_proj): Conv1D(nf=768, nx=768)
    (attn_dropout): Dropout(p=0.1, inplace=False)
    (resid_dropout): Dropout(p=0.1, inplace=False)
  )
  (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  (mlp): GPT2MLP(
    (c_fc): Conv1D(nf=3072, nx=768)
    (c_proj): Conv1D(nf=768, nx=3072)
    (act): NewGELUActivation()
    (dropout): Dropout(p=0.1, inplace=False)
  )
)

In [ ]:
# Configuration
config = model.config


In [ ]:
# Get token embeddings and position embeddings
with torch.no_grad():
    # Get initial embeddings (token embeddings + position embeddings)
    token_embeddings = model.wte(input_ids)
    position_ids = torch.arange(0, input_ids.shape[1], dtype=torch.long).unsqueeze(0)
    position_embeddings = model.wpe(position_ids)
    hidden_states = token_embeddings + position_embeddings

In [ ]:

hidden_states.shape

torch.Size([1, 12, 768])

In [ ]:
# GPT2 uses causal attention mask
batch_size, seq_length = hidden_states.size()[:2]
causal_mask = torch.tril(torch.ones((seq_length, seq_length))).view(
    1, 1, seq_length, seq_length
)

# batch_size, seq_length, causal_mask

(1, 12)

In [ ]:
# Layer norm before attention
ln_1_out = layer.ln_1(hidden_states)
ln_1_out.shape

torch.Size([1, 12, 768])

In [ ]:
# Multi-head attention
query = layer.attn.c_attn(ln_1_out)
query.shape

torch.Size([1, 12, 2304])

In [ ]:
# Split into query, key, value
query, key, value = query.split(config.hidden_size, dim=2)
query.shape, key.shape, value.shape

(torch.Size([1, 12, 768]), torch.Size([1, 12, 768]), torch.Size([1, 12, 768]))

In [ ]:
# Reshape for multi-head attention
query = query.view(batch_size, seq_length, config.n_head, config.hidden_size // config.n_head).transpose(1, 2)
key = key.view(batch_size, seq_length, config.n_head, config.hidden_size // config.n_head).transpose(1, 2)
value = value.view(batch_size, seq_length, config.n_head, config.hidden_size // config.n_head).transpose(1, 2)
query.shape, key.shape, value.shape

(torch.Size([1, 12, 12, 64]),
 torch.Size([1, 12, 12, 64]),
 torch.Size([1, 12, 12, 64]))

In [ ]:
# Compute attention scores
attn_weights = torch.matmul(query, key.transpose(-1, -2))
attn_weights = attn_weights / math.sqrt(config.hidden_size // config.n_head)
attn_weights.shape

torch.Size([1, 12, 12, 12])

In [ ]:
# Apply causal mask
attn_weights = attn_weights.masked_fill(causal_mask == 0, float('-inf'))

# Softmax and dropout
attn_weights = F.softmax(attn_weights, dim=-1)
attn_weights = F.dropout(attn_weights, p=config.attn_pdrop, training=False)
attn_weights.shape

torch.Size([1, 12, 12, 12])

In [ ]:
# Apply attention to values
attn_output = torch.matmul(attn_weights, value)

# Reshape and project
attn_output = attn_output.transpose(1, 2).contiguous().view(batch_size, seq_length, config.hidden_size)
attn_output = layer.attn.c_proj(attn_output)
attn_output.shape

torch.Size([1, 12, 768])

In [ ]:
# Add residual connection
hidden_states = hidden_states + attn_output

# Layer norm before MLP
ln_2_out = layer.ln_2(hidden_states)

# MLP
mlp_output = layer.mlp.c_fc(ln_2_out)
mlp_output = F.gelu(mlp_output)
mlp_output = layer.mlp.c_proj(mlp_output)

# Add residual connection
hidden_states = hidden_states + mlp_output

In [ ]:

hidden_states.shape

torch.Size([1, 12, 768])

In [ ]:
# Compare with original output
with torch.no_grad():
    # Extract the output from the same layer in the original model
    original_layer_output = model(input_ids, output_hidden_states=True).hidden_states[layer_idx + 1]

In [ ]:
original_layer_output.shape

torch.Size([1, 12, 768])

In [ ]:
# Check if outputs match
diff = (hidden_states - original_layer_output).abs().max().item()
print(f"Maximum difference between custom and original: {diff}")

if diff < 1e-5:
    print("✓ Implementation matches the original model!")
else:
    print("✗ Implementation does not match the original model.")

Maximum difference between custom and original: 0.0105743408203125
✗ Implementation does not match the original model.
