<a href="https://colab.research.google.com/github/addamit/LMExperiments/blob/main/TensorOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# View Operations
x = torch.randn(4, 6)
x.view(2, 12)


tensor([[ 1.9171, -0.3509,  0.7705, -0.9461,  0.2719,  0.5838,  1.1195, -1.2578,
         -0.9838,  0.2300,  0.9237,  0.0612],
        [-0.7096,  1.6347,  0.3812,  1.9932,  0.6437,  0.0686,  0.0389, -0.2757,
         -1.0571, -0.5585, -0.0932, -0.5617]])

In [3]:
x.reshape(2, 12)

tensor([[ 1.9171, -0.3509,  0.7705, -0.9461,  0.2719,  0.5838,  1.1195, -1.2578,
         -0.9838,  0.2300,  0.9237,  0.0612],
        [-0.7096,  1.6347,  0.3812,  1.9932,  0.6437,  0.0686,  0.0389, -0.2757,
         -1.0571, -0.5585, -0.0932, -0.5617]])

In [20]:

# squeeze and unsqueeze to add or remove dimensions
# The squeeze operation removes dimensions of size 1 from a tensor.
# This means if a tensor has a dimension with only one element,
# the squeeze operation will eliminate that dimension.

In [22]:
x = torch.randn(1,2)
x.shape

torch.Size([1, 2])

In [23]:
x_out = x.squeeze()
x_out

tensor([-1.0051,  1.0922])

In [24]:
x_out.shape

torch.Size([2])

In [25]:
x = torch.randn(3,2)
x.shape


torch.Size([3, 2])

In [29]:
# nothing happens if there are no dimensions of size 1.
x.squeeze().shape

torch.Size([3, 2])

In [30]:

x = torch.randn(1, 3, 1, 5)
y = x.squeeze()  # Shape becomes (3, 5)
print(y.shape)
y = x.squeeze(0)  # Shape becomes (3, 1, 5)
print (y.shape)

torch.Size([3, 5])
torch.Size([3, 1, 5])


In [31]:
# The unsqueeze operation adds a dimension of size 1 to a tensor at a specified position.
# It essentially inserts a new dimension into the tensor's shape.


In [34]:
x = torch.tensor([1])
y = x.unsqueeze(0) # will become (1, 1)
print (y.shape)
print (x)

torch.Size([1, 1])
tensor([1])


In [35]:
x = torch.randn(3, 5)
y = x.unsqueeze(0) # shape becomes (1, 3, 5)
y.shape


torch.Size([1, 3, 5])

In [36]:
y = x.unsqueeze(-1) # shape becomes (3, 5, 1)
y.shape

torch.Size([3, 5, 1])

In [38]:
# Cat/Concatenate will Join tensors along existing dimension

In [42]:
x1 = torch.randn(10, 4)
x2 = torch.randn(10, 3)
x = torch.cat([x1, x2], dim=1)
x.shape

torch.Size([10, 7])

In [47]:
# Stack will Join tensors along new dimension
x1 = torch.randn(10, 4)
x2 = torch.randn(10, 4)
x = torch.stack([x1, x2])
x.shape

torch.Size([2, 10, 4])

In [48]:
x1 = torch.tensor([1,1,1])
x2 = torch.tensor([2,2,2])
x = torch.stack([x1, x2])
x.shape

torch.Size([2, 3])

In [ ]:
# broadcasting
# Automatically expands the smaller tensor to match the shape of the larger
# tensor, enabling element-wise operations.



In [49]:
scalar = torch.tensor(5)
scalar.shape

torch.Size([])

In [50]:
vector = torch.tensor([1, 2, 3])
vector.shape

torch.Size([3])

In [53]:
result = scalar + vector # possible due to broadcasting
result # scalar is expanded to have the same shape as the vector, resulting in element-wise addition: [5, 5, 5]

tensor([6, 7, 8])

Rules of Broadcasting

Dimension Matching: Starting from the trailing dimensions, the dimensions of the tensors must either be equal or one of them must be 1.  

Expansion: If a dimension is 1, it is automatically expanded to match the corresponding dimension of the other tensor.  

Compatibility: If the dimensions are not compatible, a runtime error will occur.
